In [11]:
#basics of pytorch & some numpy

import torch

x = torch.empty(1,2,3, dtype= torch.int)

print(x.dtype)

torch.int32


In [13]:
x = torch.tensor([1,2,3])

print(x)

tensor([1, 2, 3])


In [14]:
x = torch.rand(2,3)

print(x)

tensor([[0.6980, 0.1674, 0.0322],
        [0.1883, 0.6944, 0.6623]])


In [17]:
y = torch.rand(2,3)
print(y)

#underscore functions does in place addition
y.add_(x)
print(y)

tensor([[0.2402, 0.3297, 0.9110],
        [0.0949, 0.4532, 0.7298]])
tensor([[0.9382, 0.4971, 0.9432],
        [0.2832, 1.1477, 1.3921]])


In [22]:
z = torch.rand(5, 4)
print(z)

print(z[:,1])

tensor([[0.1492, 0.9004, 0.0713, 0.1102],
        [0.3531, 0.9763, 0.2891, 0.8836],
        [0.6328, 0.3073, 0.6923, 0.2183],
        [0.1922, 0.9681, 0.7457, 0.8379],
        [0.2021, 0.0866, 0.1803, 0.3327]])
tensor([0.9004, 0.9763, 0.3073, 0.9681, 0.0866])


In [24]:
x = torch.rand(2,3,4)
print(x)
y = x.view(4,6)
print(y)

tensor([[[0.9032, 0.8318, 0.5061, 0.7951],
         [0.1601, 0.3905, 0.3037, 0.7515],
         [0.3543, 0.4366, 0.6939, 0.3204]],

        [[0.9514, 0.3644, 0.0288, 0.7751],
         [0.8659, 0.3039, 0.3031, 0.2404],
         [0.2223, 0.1410, 0.7141, 0.1361]]])
tensor([[0.9032, 0.8318, 0.5061, 0.7951, 0.1601, 0.3905],
        [0.3037, 0.7515, 0.3543, 0.4366, 0.6939, 0.3204],
        [0.9514, 0.3644, 0.0288, 0.7751, 0.8659, 0.3039],
        [0.3031, 0.2404, 0.2223, 0.1410, 0.7141, 0.1361]])
