In [3]:
#auto grad

import torch

x = torch.randn(5, requires_grad = True)
print(x)

tensor([-0.8895, -1.1564,  0.8982,  1.3924,  0.4621], requires_grad=True)


In [10]:
y = x + 2
print(y)

# z = y
# z = z.mean()
y = y.mean()
y.backward()
# y = y.mean()

print(x.grad)

tensor([1.1105, 0.8436, 2.8982, 3.3924, 2.4621], grad_fn=<AddBackward0>)
tensor([1.2884, 1.0749, 2.7185, 3.1139, 2.3697])
